# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: first-test
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: first-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: tusharkapadi1/web-first-test:<+pipeline.variables.imageTag>
          ports:
            - containerPort: 3000
